# Based on https://angular.io/guide/testing#set-up-continuous-integration
steps:
  - name: node:10.16.3
    entrypoint: chmod
    # The circleci images run as the 'circleci' user, but /workspace is owned by root
    # This chmod command enables the circleci user to write to the /workspace directory,
    # which is necessary for the subsequent steps to work
    args: ['-R', 'a+w', '.']
  - name: circleci/node:10-browsers
    entrypoint: yarn
    args: ['install', '--prefix', '/workspace']
    env:
    - 'HOME=/workspace'
    - 'PREFIX=/workspace'
  - name: circleci/node:10-browsers
    entrypoint: yarn
    args: ['test', '--no-watch', '--no-progress', '--browsers=ChromeHeadlessCI']
    env:
    - 'HOME=/workspace'
    - 'PREFIX=/workspace'
