# Based on https://angular.io/guide/testing#set-up-continuous-integration
steps:
  - name: circleci/node:10-browsers
    entrypoint: npm
    args: ['install']
  - name: circleci/node:10-browsers
    entrypoint: npm
    args: ['test', '--', '--no-watch']
