# Based on https://angular.io/guide/testing#set-up-continuous-integration
steps:
  - name: node:10.16.3
    entrypoint: chmod
    args: ['-R', 'a+w', '.']
  - name: circleci/node:10-browsers
    entrypoint: yarn
    args: ['install', '--prefix', '/workspace']
    env:
    - 'HOME=/workspace'
    - 'PREFIX=/workspace'
  - name: circleci/node:10-browsers
    entrypoint: yarn
    args: ['test', '--no-watch', '--no-progress', '--browsers=ChromeHeadlessCI']
    env:
    - 'HOME=/workspace'
    - 'PREFIX=/workspace'
