# Based on https://angular.io/guide/testing#set-up-continuous-integration
steps:
  - name: node:10.16.3
    entrypoint: npm
    args: ['install']
  - name: selenium/standalone-chrome:3.141.59
  - name: node:10.16.3
    entrypoint: npm
    args: ['test', '--', '--no-watch']
