# Based on https://angular.io/guide/testing#set-up-continuous-integration
steps:
  - name: node:10.16.3
    entrypoint: chmod
    args: ['a+w', '.']
  - name: node:10.16.3
    entrypoint: ls
    args: ['-la']   
  - name: circleci/node:10-browsers
    entrypoint: whoami
  - name: circleci/node:10-browsers
    entrypoint: yarn
    args: [cache', 'dir']
    env:
    - 'HOME=/workspace'
  - name: circleci/node:10-browsers
    entrypoint: yarn
    args: ['config', '--prefix', '/workspace', 'set', 'cache-folder', '/workspace/yarn-cache']
    env:
    - 'HOME=/workspace'
  - name: circleci/node:10-browsers
    entrypoint: yarn
    args: ['cache', 'dir']
    env:
    - 'HOME=/workspace'
  - name: circleci/node:10-browsers
    entrypoint: yarn
    args: ['install', '--prefix', '/workspace']
    env:
    - 'HOME=/workspace'
    - 'PREFIX=/workspace'
  - name: circleci/node:10-browsers
    entrypoint: yarn
    args: ['test', '--no-watch', '--prefix', '/workspace/yarn']
    env:
    - 'HOME=/workspace'
    - 'PREFIX=/workspace'
